const router=require('express').Router();
const { asyncHandler }=require('../utils/asyncHandler');
const { requireAuth, requireRoles }=require('../middleware/authJwt');
const ctl=require('../controllers/catalogos.controller').proveedores;
router.use(requireAuth);
router.get('/', asyncHandler(ctl.listar));
router.post('/', requireRoles('ADMIN','VENDEDOR'), asyncHandler(ctl.crear));
router.get('/:id', asyncHandler(ctl.get));
router.patch('/:id', requireRoles('ADMIN','VENDEDOR'), asyncHandler(ctl.actualizar));
router.patch('/:id/estado', requireRoles('ADMIN'), asyncHandler(ctl.estado));
module.exports=router;
